services:

  controller:
    environment:
      # required to directly print() towards stdout - activates flush always
      PYTHONUNBUFFERED: 1
    build:
      context: controller
      target: builder
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    expose:
      - 8000
    ports:
      - '8000:8000'
    volumes:
      - ./database:/database
    develop:
      watch:
        - action: rebuild
          path: .

  runner:
    environment:
      # required to directly print() towards stdout - activates flush always
      PYTHONUNBUFFERED: 1
    build:
      context: runner
      target: builder
    links:
      - controller