services:
  api:
    environment:
      # required to directly print() towards stdout - activates flush always
      PYTHONUNBUFFERED: 1
    build:
      context: api
      dockerfile: Dockerfile
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    expose:
      - 8000
    ports:
      #extern:intern
      - '8000:8000'
    volumes:
      - ./database:/database

  runner:
    depends_on:
      - api
    links:
      - api
    environment:
      # required to directly print() towards stdout - activates flush always
      PYTHONUNBUFFERED: 1
    build:
      context: runner
      dockerfile: Dockerfile

networks:
  default:
    driver: bridge