services:
  api:
    environment:
      # required to directly print() towards stdout - activates flush always
      PYTHONUNBUFFERED: 1
    build:
      context: api
      dockerfile: Dockerfile
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    expose:
      - 80
    # for direct debudding and deploy via pycharm
    ports:
      - "8001:80"
    volumes:
      - ./database:/database
      - ./config:/config

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    expose:
      - 3000
    ports:
      - "3000:3000"
    environment:
#      - API_URL=http://localhost:8000/api/frontend
      - API_URL=http://vestaboard.imount.de/api/frontend

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
      - frontend

  runner:
    depends_on:
      - api
    links:
      - api
    environment:
      # required to directly print() towards stdout - activates flush always
      PYTHONUNBUFFERED: 1
    build:
      context: runner
      dockerfile: Dockerfile
    restart: on-failure

networks:
  default:
    driver: bridge