import string
import vesta

class AbstractScene:

    # last message string generated by the scene. Needed for debug reasons
    lastGeneratedMessage: string = None

    def execute(self, vboard):
        self.lastGeneratedMessage = "Hello, World"
        message = vesta.encode_text(self.lastGeneratedMessage)
        vboard.write_message(message)



class DemoScene(AbstractScene):
    def execute(self, vboard):
        self.lastGeneratedMessage = "{67} demo scene {68}"
        message = vesta.encode_text(self.lastGeneratedMessage)
        vboard.write_message(message)
