import string
import vesta

class AbstractScene:

    # last message string generated by the scene. Needed for debug reasons
    lastGeneratedMessage: string = None

    # opt-out possibility if the scene does not have some meaningful content.
    # Used for example within the WasteCalendarScene
    scene_enabled: bool = True

    # default priority. Steers the order of scenes
    priority: int = 100

    def execute(self, vboard):
        self.lastGeneratedMessage = "Hello, World"
        message = vesta.encode_text(self.lastGeneratedMessage)
        vboard.write_message(message)



class DemoScene(AbstractScene):
    def execute(self, vboard):
        self.lastGeneratedMessage = "{67} demo scene {68}"
        message = vesta.encode_text(self.lastGeneratedMessage)
        vboard.write_message(message)
