name: Create all relevant containers (API+runner) and pushes them to docker.hub

on:
  push:
    branches:
      - main

jobs:
  set-vars:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set enviroment
        shell: bash
        run: |
          echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
          echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> "$GITHUB_ENV"
          echo "secret=second_value" >> "$GITHUB_ENV"
      - name: Read enviroment
        shell: bash
        run: |
          echo "BRANCH: ${{ env.branch }}"
          echo "SHA_SHORT: ${{ env.sha_short }}"
          echo "secret: ${{ env.secret }}"
          
  build-api:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'release me')"

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKERHUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Build and push Docker image
      run: |
        cd api
        echo "hurra ${{ env.secret }}" > "git-version.txt"
        docker buildx create --use
        docker buildx build \
          --file Dockerfile \
          --tag jakez/vestascenes-api:latest \
          --push .

  build-runner:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'release me')"

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKERHUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Build and push Docker image
      run: |
        cd runner
        docker buildx create --use
        docker buildx build \
          --file Dockerfile \
          --tag jakez/vestascenes-runner:latest \
          --push .

    env:
      DOCKER_CLI_EXPERIMENTAL: enabled
      DOCKER_BUILDKIT: 1
