name: Create all relevant containers (API+runner) and pushes them to docker.hub

on:
  push:
    branches:
      - releases

jobs:
  set-vars:
    runs-on: ubuntu-latest
    outputs:
      sha_short: ${{ steps.writestep.outputs.sha_short }}
    steps:
      - uses: actions/checkout@v1
      - id: writestep
        name: Set enviroment
        shell: bash
        run: |
          echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_OUTPUT"
          
  read-vars-on-another-job:
    runs-on: ubuntu-latest
    needs: set-vars
    steps:
      - name: Sample task to read vars
        env:
          sha_short: ${{needs.set-vars.outputs.sha_short}}
        shell: bash
        run: |
          echo "sha short: $sha_short"
          
  build-api:
    runs-on: ubuntu-latest
    needs: set-vars
    # if: "contains(github.event.head_commit.message, 'release me')"

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKERHUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Build and push Docker image
      env:
          sha_short: ${{needs.set-vars.outputs.sha_short}}
      run: |
        cd api
        echo "da ist er $sha_short"
        echo "$sha_short" > "git-version.txt"
        docker buildx create --use
        docker buildx build \
          --file Dockerfile \
          --tag jakez/vestascenes-api:latest \
          --push .

  build-runner:
    runs-on: ubuntu-latest
    needs: set-vars
    # if: "contains(github.event.head_commit.message, 'release me')"

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKERHUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Build and push Docker image
      run: |
        cd runner
        pip install -e .
        docker buildx create --use
        docker buildx --debug build \
          --file Dockerfile \
          --tag jakez/vestascenes-runner:latest \
          --push .

    env:
      DOCKER_CLI_EXPERIMENTAL: enabled
      DOCKER_BUILDKIT: 1
