name: Create all relevant containers (API+runner) and pushes them to docker.hub

on:
  push:
    branches:
      - main

jobs:
  build-api:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, 'release me')"

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKERHUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Build and push Docker image
      run: |
        cd api
        docker buildx create --use
        docker buildx build \
          --file Dockerfile \
          --tag jakez/vestascenes-api:latest \
          --push .

    env:
      DOCKER_CLI_EXPERIMENTAL: enabled
      DOCKER_BUILDKIT: 1
